name: Build
on: 
  push:
    branches-ignore:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3            
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'
      - name: Build with Gradle
        run: ./gradlew --no-daemon build

      - name: Upload jar cache
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.sha }}-ukulele
          path: ukulele.jar