name: Deploy Container Apps

on:
  workflow_call:
    inputs:
      github-environment:
        description: 'Target Github Environment'
        required: true
        type: string
      environment:
        description: 'Target environment (dev, prod)'
        required: true
        type: string
    secrets:
      AZURE_CLIENT_ID:
        description: 'Azure Service Principal Client ID'
        required: true
      AZURE_TENANT_ID:
        description: 'Azure Tenant ID'
        required: true
      AZURE_SUBSCRIPTION_ID:
        description: 'Azure Subscription ID'
        required: true
      TS_OAUTH_CLIENT_ID:
        description: 'Tailscale OAuth Client ID'
        required: true
      TS_OAUTH_SECRET:
        description: 'Tailscale OAuth Secret'
        required: true
      SSH_PRIVATE_KEY:
        description: 'SSH Private Key for server access'
        required: true
      SSH_HOST:
        description: 'SSH Host for server access'
        required: true

env:
  AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

permissions:
  id-token: write
  contents: read

jobs:
  deploy-bot:
    runs-on: ubuntu-latest
    environment: ${{ inputs.github-environment }}
    
    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Install PowerShell
        run: |
          sudo apt-get update
          sudo apt-get install -y powershell

      - name: Deploy Bot Container App
        run: |
          pwsh -File Deployment/scripts/deploy-container-app.ps1 \
            -ProjectName "bot" \
            -DockerfilePath "Src/Chrisalaxelrto.Bot/Dockerfile" \
            -Environment "${{ inputs.environment }}"

  deploy-music-streamer:
    runs-on: ubuntu-latest
    environment: ${{ inputs.github-environment }}
    
    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
          use-cache: 'true'

      - name: Install PowerShell
        run: |
          sudo apt-get update
          sudo apt-get install -y powershell

      - name: Deploy Bot Container App
        run: |
          pwsh -File Deployment/scripts/deploy-container-app.ps1 \
            -ProjectName "music" \
            -DockerfilePath "Src/Chrisalaxelrto.MusicStreamer/Dockerfile" \
            -Environment "${{ inputs.environment }}" \
            -UpdateContainerApp $False
            
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: SSH into server and run commands
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_HOST }} '
          sudo az login --identity
          sudo az acr login --name chrisalaxelrtoacrprod
          
          sudo docker pull chrisalaxelrtoacrprod.azurecr.io/music:latest
          
          sudo docker stop music-container || true
          sudo docker rm music-container || true
          
          sudo docker run -d \
            --name music-container \
            --network host \
            --restart unless-stopped \
            chrisalaxelrtoacrprod.azurecr.io/music:latest
          '
