name: Deploy container apps

# on:
#   push:
#     branches:
#       - main
#     paths:
#       - 'Src/**'
#   workflow_dispatch:

jobs:
  deploy-prod:
    name: Deploy containers to production
    uses: ./.github/workflows/deploy-container-apps-template.yml
    with:
      environment: prod
      github-environment: Chrisalaxelrto
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      TS_OAUTH_CLIENT_ID: ${{ secrets.TS_OAUTH_CLIENT_ID }}
      TS_OAUTH_SECRET: ${{ secrets.TS_OAUTH_SECRET }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SSH_HOST: ${{ secrets.SSH_HOST }}