name: Build and deploy to Chrisalaxelrto
on: 
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3            
      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: 18
          distribution: 'adopt'
      - name: Build with Gradle
        run: ./gradlew --no-daemon build

      - name: Upload jar artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.sha }}-ukulele
          path: ukulele.jar

  deployment:
      needs: build
      runs-on: ubuntu-latest
      environment: Chrisalaxelrto
      steps:
        - name: Add mask
          run: |
            echo "::add-mask::${{ secrets.SUDO_PASS }}" 
        - uses: 1arp/create-a-file-action@0.2
          with:
            path: .
            file: 'ukulele.yml'
            content: |
              config:
                token: "${{ secrets.DISCORD_TOKEN }}"  # Your discord bot token
                shards: 1 # Number of shards to create. 1 works for most bots
                prefix: "."  # Prefix to invoke commands with
                database: "./database" # Database filename
                game: "Now in the cloud :D" # Status message shown when your bot is online
                trackDurationLimit: 0 # Maximum limit of track duration in minutes. Set to 0 for unlimited
                announceTracks: true # Announce the start of a track
                azureToken: "${{ secrets.AZURE_VISION_API_TOKEN }}" # Azure token for API calls
                azureEndpoint: "${{ secrets.AZURE_VISION_API_ENDPOINT }}" #Azure endpoint for API calls
                openAIToken: "${{ secrets.OPENAI_API_ENDPOINT }}"
                ytAuthToken: "${{ secrets.YT_AUTH_TOKEN }}" 
                visitorData: "${{ secrets.YT_VISITOR_DATA }}" 
                poToken: "${{ secrets.YT_PO_TOKEN }}" 
                elevenLabsToken: "${{ secrets.ELEVENLABS_TOKEN }}"


        - uses: actions/download-artifact@v4
          with:
            name: ${{ github.sha }}-ukulele
            
        - name: Connect to Wireguard VPN
          uses: egor-tensin/setup-wireguard@v1.2.0
          with:
            # Endpoint in the HOST:PORT format
            endpoint:  ${{ secrets.VPN_HOST }}
            # Public key of the endpoint
            endpoint_public_key: ${{ secrets.VPN_HOST_PUBLIC_KEY }}
            # Comma-separated list of IP addresses
            ips:  ${{ secrets.VPN_IP}}
            # Comma-separated list of netmasks
            allowed_ips:  ${{ secrets.VPN_ALLOWED_IPS}}
            # Private key
            private_key:  ${{ secrets.VPN_PRIVATE_KEY}}
            # Useful for NAT traversal
            keepalive:   ${{ secrets.VPN_KEEPALIVE}}
            
        - name: Stopping ukulele on server
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            key: ${{ secrets.KEY }}
            script: echo ${{ secrets.SUDO_PASS }} | sudo -S systemctl stop ukulele

        - name: Copy jar file
          uses: appleboy/scp-action@master
          with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            key: ${{ secrets.KEY }}
            source: "ukulele.jar"
            target: ${{ secrets.DIRECTORY }}

        - name: Copy config file
          uses: appleboy/scp-action@master
          with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            key: ${{ secrets.KEY }}
            source: "ukulele.yml"
            target: ${{ secrets.DIRECTORY }}

        - name: Restarting ukulele on server
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            key: ${{ secrets.KEY }}
            script: echo ${{ secrets.SUDO_PASS }} | sudo -S systemctl start ukulele
