name: Deploy Infrastructure

on:
  workflow_call:
    inputs:
      github-environment:
        description: 'Target Github Environment'
        required: true
        type: string
      environment:
        description: 'Target environment (dev, prod)'
        required: true
        type: string
      container-image:
        description: 'Container image to deploy'
        required: false
        type: string
        default: 'mcr.microsoft.com/dotnet/runtime:8.0'
    secrets:
      AZURE_CLIENT_ID:
        description: 'Azure Service Principal Client ID'
        required: true
      AZURE_TENANT_ID:
        description: 'Azure Tenant ID'
        required: true
      AZURE_SUBSCRIPTION_ID:
        description: 'Azure Subscription ID'
        required: true
      DISCORD_BOT_TOKEN:
        description: 'Discord Bot Token'
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy infrastructure to ${{ inputs.environment }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.github-environment }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Extract location from parameter file
      id: params
      run: |
        PARAM_FILE="Deployment/parameters/parameters.${{ inputs.environment }}.json"
        LOCATION=$(jq -r '.parameters.location.value // .parameters.location.defaultValue // empty' "$PARAM_FILE")
        if [ -z "$LOCATION" ]; then
          echo "Error: Could not extract location from $PARAM_FILE"
          exit 1
        fi
        APP_NAME=$(jq -r '.parameters.applicationName.value // .parameters.applicationName.defaultValue // empty' "$PARAM_FILE")
        if [ -z "$APP_NAME" ]; then
          echo "Error: Could not extract application name from $PARAM_FILE"
          exit 1
        fi
        echo "location=$LOCATION" >> $GITHUB_OUTPUT
        echo "Location: $LOCATION"
        echo "app_name=$APP_NAME" >> $GITHUB_OUTPUT
        echo "App Name: $APP_NAME"

    - name: Create Resource Group
      run: |
        az group create \
          --name ${{ steps.params.outputs.app_name }} \
          --location "${{ steps.params.outputs.location }}" \
          --tags Environment=${{ inputs.environment }} Application=chrisalaxelrto-bot ManagedBy=GitHub-Actions

    - name: Deploy Bicep template
      id: deploy
      run: |
        DEPLOYMENT_NAME="deploy-$(date +%Y%m%d-%H%M%S)"
        
        az deployment group create \
          --resource-group ${{ steps.params.outputs.app_name }} \
          --template-file Deployment/main.bicep \
          --parameters @Deployment/parameters/parameters.${{ inputs.environment }}.json \
          --parameters containerImage="${{ inputs.container-image }}" \
          --parameters discordBotToken="${{ secrets.DISCORD_BOT_TOKEN }}" \
          --name $DEPLOYMENT_NAME \
          --verbose
        
        echo "deployment-name=$DEPLOYMENT_NAME" >> $GITHUB_OUTPUT