name: Deploy Container Apps

on:
  workflow_call:
    inputs:
      github-environment:
        description: 'Target Github Environment'
        required: true
        type: string
      environment:
        description: 'Target environment (dev, prod)'
        required: true
        type: string
    secrets:
      AZURE_CLIENT_ID:
        description: 'Azure Service Principal Client ID'
        required: true
      AZURE_TENANT_ID:
        description: 'Azure Tenant ID'
        required: true
      AZURE_SUBSCRIPTION_ID:
        description: 'Azure Subscription ID'
        required: true
      TAILSCALE_AUTH_KEY:
        description: 'Tailscale Auth Key'
        required: true

env:
  AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

permissions:
  id-token: write
  contents: read

jobs:
  deploy-bot:
    runs-on: ubuntu-latest
    environment: ${{ inputs.github-environment }}
    
    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Install PowerShell
        run: |
          sudo apt-get update
          sudo apt-get install -y powershell

      - name: Deploy Bot Container App
        run: |
          pwsh -File Deployment/scripts/deploy-container-app.ps1 \
            -ProjectName "bot" \
            -DockerfilePath "Src/Chrisalaxelrto.Bot/Dockerfile" \
            -Environment "${{ inputs.environment }}"

  deploy-musicstreamer:
    runs-on: ubuntu-latest
    environment: ${{ inputs.github-environment }}
    
    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Install PowerShell
        run: |
          sudo apt-get update
          sudo apt-get install -y powershell

      - name: Deploy Music Streamer Container App
        run: |
          pwsh -File Deployment/scripts/deploy-container-app.ps1 \
            -ProjectName "music" \
            -DockerfilePath "Src/Chrisalaxelrto.MusicStreamer/Dockerfile" \
            -Environment "${{ inputs.environment }}"
            -TailscaleAuthKey "${{ secrets.TAILSCALE_AUTH_KEY }}"