name: Build and deploy to Chrisalaxelrto
on: 
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3            
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'
      - name: Build with Gradle
        run: ./gradlew --no-daemon build

      - name: Upload jar artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.sha }}-ukulele
          path: ukulele.jar

  deployment:
      needs: build
      runs-on: ubuntu-latest
      environment: Chrisalaxelrto
      steps:
        - name: Add mask
          run: |
            echo "::add-mask::${{ secrets.SUDO_PASS }}" 
        - uses: 1arp/create-a-file-action@0.2
          with:
            path: .
            file: 'ukulele.yml'
            content: |
              config:
                token: "${{ secrets.DISCORD_TOKEN }}"  # Your discord bot token
                shards: 1 # Number of shards to create. 1 works for most bots
                prefix: "."  # Prefix to invoke commands with
                database: "./database" # Database filename
                game: "Now in the cloud :D" # Status message shown when your bot is online
                trackDurationLimit: 0 # Maximum limit of track duration in minutes. Set to 0 for unlimited
                announceTracks: true # Announce the start of a track
                azureToken: "${{ secrets.AZURE_VISION_API_TOKEN }}" # Azure token for API calls
                azureEndpoint: "${{ secrets.AZURE_VISION_API_ENDPOINT }}" #Azure endpoint for API calls
        
        - uses: actions/download-artifact@v3
          with:
            name: ${{ github.sha }}-ukulele
        - name: Stopping ukulele on server
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            key: ${{ secrets.KEY }}
            script: echo ${{ secrets.SUDO_PASS }} | sudo -S systemctl stop ukulele

        - name: Copy jar file
          uses: appleboy/scp-action@master
          with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            key: ${{ secrets.KEY }}
            source: "ukulele.jar"
            target: ${{ secrets.DIRECTORY }}

        - name: Copy config file
          uses: appleboy/scp-action@master
          with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            key: ${{ secrets.KEY }}
            source: "ukulele.yml"
            target: ${{ secrets.DIRECTORY }}

        - name: Restarting ukulele on server
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            key: ${{ secrets.KEY }}
            script: echo ${{ secrets.SUDO_PASS }} | sudo -S systemctl start ukulele