name: Deploy infrastructure

on:
  push:
    branches:
      - main
    paths:
      - 'Deployment/**'
  workflow_dispatch:

jobs:
  deploy-prod:
    name: Deploy infrastructure to Production Environment
    uses: ./.github/workflows/deploy-infrastructure-template.yml
    with:
      environment: prod
      github-environment: Chrisalaxelrto
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
      DISCORD_BOT_TOKEN_DEV: ${{ secrets.DISCORD_BOT_TOKEN_DEV }}
      YOUTUBE_COOKIES: ${{ secrets.YOUTUBE_COOKIES }}
      SSH_PUB_KEY: ${{ secrets.SSH_PUB_KEY }}